cmake_minimum_required(VERSION 4.2)
project(Algoritmos_y_Estructuras_de_Datos___Snippets_)

set(CMAKE_CXX_STANDARD 14)

add_executable(Algoritmos_y_Estructuras_de_Datos___Snippets_
        Vector.cpp
        String.cpp
        Array.cpp
        Lista_simple.cpp
        Lista_circular.cpp
        Lista_doblemente_enlazada.cpp
        Lista_doble_puntero.cpp
        main.cpp
        Ejercicios_Sem_3/Books_Exchange.cpp
        Plantilla.cpp
        Ejercicios_Sem_3/Cajas.cpp
        Ejercicios_Sem_3/Josephus.cpp
        Ejercicios_Sem_3/Polinomios.cpp
        "Ejercicios_Sem_3/Round Robin.cpp"
        "Ejercicios_Sem_3/Doubly Linked List.cpp"
        Ejercicios_Sem_3/Cajas_ptr.cpp
        Ejercicios_Sem_3/Apuntes.cpp
        Ejercicios_Sem_3/stack,queue,deque/Stack.cpp
        Ejercicios_Sem_3/stack,queue,deque/queue.cpp
        Ejercicios_Sem_3/stack,queue,deque/deque.cpp
        unordered_map.cpp
        Ejercicios_Sem_3/stack,queue,deque/H_Maximum_Trace.cpp
        Ejercicios_Sem_3/stack,queue,deque/D.cpp
        Ejercicios_Sem_5/A.cpp
        hash_table.cpp
        Ejercicios_Sem_5/B.cpp
        Ejercicios_Sem_5/D.cpp
        Ejercicios_Sem_5/E.cpp
        Ejercicios_Sem_6/BST.cpp
        Ejercicios_Sem_5/C.cpp
        Ejercicios_Sem_5/F.cpp
        Ejercicios_Sem_5/G.cpp
        Ejercicios_Sem_5/H.cpp
        Ejercicios_Sem_5/I.cpp
        Ejercicios_Sem_5/J.cpp
        Ejercicios_Sem_5/Lista_/Contains_Duplicate.cpp
        Ejercicios_Sem_5/Lista_/Two_Sum.cpp
        "Ejercicios_Sem_5/Lista_/Registration_System.cpp"
        "Ejercicios_Sem_5/Lista_/Contains_Duplicate II.cpp"
        Ejercicios_Sem_5/Lista_/Subarray_Sums_I.cpp
        Ejercicios_Sem_5/Lista_/Distinct_Values_Subarrays.cpp
        Ejercicios_Sem_5/Lista_/Same_Differences.cpp
        Ejercicios_Sem_5/Lista_/Group_Anagrams.cpp
        Ejercicios_Sem_5/Lista_/Divisible_Pairs.cpp
        Ejercicios_Sem_5/Lista_/Subarray_Sums_II.cpp
        Ejercicios_Sem_5/Lista_/Romantic_Glasses.cpp
        "Ejercicios_Sem_5/Lista_/Monocarp's String.cpp"
)
