cmake_minimum_required(VERSION 4.2)
project(Algoritmos_y_Estructuras_de_Datos___Snippets_)

set(CMAKE_CXX_STANDARD 14)

add_executable(Algoritmos_y_Estructuras_de_Datos___Snippets_
        Vector.cpp
        String.cpp
        Array.cpp
        Lista_simple.cpp
        Lista_circular.cpp
        Lista_doblemente_enlazada.cpp
        Lista_doble_puntero.cpp
        main.cpp
        Ejercicios_Sem_3/Books_Exchange.cpp
        Plantilla.cpp
        Ejercicios_Sem_3/Cajas.cpp
        Ejercicios_Sem_3/Josephus.cpp
        Ejercicios_Sem_3/Polinomios.cpp
        "Ejercicios_Sem_3/Round Robin.cpp"
        "Ejercicios_Sem_3/Doubly Linked List.cpp"
        Ejercicios_Sem_3/Cajas_ptr.cpp)
